name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Debug current directory
        run: |
          echo "✅ 현재 디렉토리 확인"
          pwd
          ls -al

      - name: Get dependencies
        run: |
          cd $GITHUB_WORKSPACE
          flutter pub get

      - name: Build IPA
        run: |
          cd $GITHUB_WORKSPACE
          flutter build ipa --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Debug current directory
        run: |
          echo "✅ 현재 디렉토리 확인"
          pwd
          ls -al

      - name: Get dependencies
        run: |
          cd $GITHUB_WORKSPACE
          flutter pub get

      - name: Build IPA
        run: |
          cd $GITHUB_WORKSPACE
          flutter build ipa --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
