name: Build iOS .ipa

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: pc

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
        working-directory: pc

      - name: Build for iOS (no codesign)
        run: flutter build ios --no-codesign
        working-directory: pc

      - name: Manually Package IPA Without Codesign
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
        working-directory: pc

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: pc/build/ios/ipa/Runner.ipa
